### ISSUE TITLE
Use Vuetify Theming

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/wegue#202]
It would be very handy to use the Vuetify theming mechanism. Goal would be to get rid of the `baseColor` property in the app-conf, which has to be passed through all components and instead a defining an optional Vuetify theme in the app-config.
Default style of a Wegue app could be a predefined standard Vuetify theme.

See 
  - https://v2.vuetifyjs.com/en/customization/presets/ 
  - https://vuetifyjs.com/en/features/presets/#generator 
  - https://material.io/design/material-theming/implementing-your-theme.html#color

**Comment by JakobMiksch** [comment]
Hi @ntma , it seems there is no current work done on this topic. Hence, a contribution would be very welcome. 
Feel free to ask if there any questions. There is a also a Wegue chat on [gitter](https://gitter.im/wegue/community)

**Comment by ntma** [comment]
Perfect, I'll see what I can do 👍

**Comment by ntma** [comment]
Hi @fschmenger ,

Thank you for this outline :+1: 

Allow me to number your bullets to ease the discussion. So:
1. seems to be fairly easy. Wegue will start using the 'primary' and 'secondary' classes to theme the UI according to the material design system;
2. no questions here for now;
3. basically instead of providing a `baseColor`, we want to provide a preset config. Should this config be placed in the `app-config.json`?

**Comment by fschmenger** [comment]
Hi @ntma, I haven't been very concise in my description but happy to see you got it right!

Yes, regarding point 3 I would suggest to support an optional declaration of a top level 'theme' attribute in app-config.json (this is what I meant when refering to 'application context'). 
I'm a bit busy until mid of next week but will follow this issue in case you have any further question.
