### ISSUE TITLE
Add overview map component

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/wegue#204]
Wrap the [OpenLayers overview map](https://openlayers.org/en/latest/apidoc/module-ol_control_OverviewMap-OverviewMap.html) component into a Vue / Wegue component. Similar to the [GeoExt solution](https://geoext.github.io/geoext3/master/examples/component/overviewMap.html).

**Comment by fschmenger** [comment]
I have a little spare time this week so I decided to get working on this.

@chrismayer @JakobMiksch 
Basically I see 2 implementation options:
* Option 1 would be a custom control with an open/closer located on the map and a top level app-conf configuration (somewhat similar to the behavior of `BgLayerSwitcher`).
* Option 2 would be a `ModuleCard` based implementation (with a general option to supress the module card header - like in  #243). The overview map could then be toggled like a normal module via a corresponding toolbarbutton and can be also placed on the sidebar (although I dont see much use for that). App-conf configuration object would then be among `modules.`

I tend to go with option 1, since this is the symetrical approach to what we have for the layer switcher, but option 2 is definetely feasible.
Which solution do you prefer?
